# Generated by Django 4.2.3 on 2024-01-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Iris',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sepal_length', models.FloatField()),
                ('petal_length', models.FloatField()),
                ('sepal_width', models.FloatField()),
                ('iris_class', models.IntegerField()),
            ],
        ),
    ]
