# Generated by Django 4.2.3 on 2024-01-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irises_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iris',
            name='petal_width',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
